# Package overrides per package manager.
# Docker packages are installed from official Docker repository.
# See docker.sh for the actual installation process.
# Example:
# [apt]
# go = "golang"

[apt]
go = "golang"
openjdk-17-jdk = "openjdk-17-jdk"

[pacman]
go = "go"
docker = "docker"
docker-compose = "docker-compose"
jdk17-openjdk = "jdk17-openjdk"

[dnf]
go = "golang"
java-17-openjdk-devel = "java-17-openjdk-devel"
