format = "$directory$character"

[directory]
format = "[$path]($style) "
style = "bold cyan"
truncation_length = 1
truncate_to_repo = false

[character]
success_symbol = "[➜](bold cyan) "
error_symbol = "[➜](bold red) "
