[character]
success_symbol = "[➜](bold cyan)"
error_symbol = "[➜](bold red)"


"$schema" = 'https://starship.rs/config-schema.json'

[bun]
format = "($style)"

[buf]
format = "with ($style)"

[c]
format = "[$symbol($name)]($style)"

[cmake]
format = "($style)"

[cobol]
format = "($style)"

[cpp]
format = "[$symbol($name)]($style)"

[crystal]
format = "($style)"

[daml]
format = "($style)"

[dart]
format = "($style)"

[deno]
format = "($style)"

[dotnet]
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
format = '($style)'

[elm]
format = '($style)'

[erlang]
format = '($style)'

[fennel]
format = '($style)'

[fortran]
format = '($style)'

[gleam]
format = '($style)'

[golang]
format = '($style)'

[gradle]
format = '($style)'

[haskell]
format = '($style)'

[haxe]
format = '($style)'

[helm]
format = '($style)'

[java]
format = '($style)'

[julia]
format = '($style)'

[kotlin]
format = '($style)'

[lua]
format = '($style)'

[maven]
format = '($style)'

[meson]
format = '($style)'

[mojo]
format = 'with ($style)'

[nim]
format = '($style)'

[nodejs]
format = '($style)'

[ocaml]
format = '[$symbol(\($switch_indicator$switch_name\) )]($style)'

[odin]
format = '($style)'

[opa]
format = '($style)'

[perl]
format = '($style)'

[php]
format = '($style)'

[pixi]
format = '[$symbol($environment )]($style)'

[pulumi]
format = '[$symbol$stack]($style)'

[purescript]
format = '($style)'

[python]
format = '($style)'

[quarto]
format = '($style)'

[raku]
format = '($style)'

[red]
format = '($style)'

[rlang]
format = '($style)'

[ruby]
format = '($style)'

[rust]
format = '($style)'

[scala]
format = '($style)'

[solidity]
format = '($style)'

[swift]
format = '($style)'

[typst]
format = '($style)'

[vagrant]
format = '($style)'

[vlang]
format = '($style)'

[xmake]
format = "($style)"

[zig]
format = '($style)'
